version: '3'

services:
  backend:
    image: python:3.12
    command: python /app/backend.py
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: backend
      POSTGRES_DB: dashboard
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./backend/sql:/docker-entrypoint-initdb.d

  frontend:
    image: node:21
    command: npm run dev
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
