DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS appointments;
DROP TABLE IF EXISTS sensors;
DROP TABLE IF EXISTS hardware;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS buildings;
DROP TABLE IF EXISTS organisations;

DROP TYPE IF EXISTS hardware_protocols;
DROP TYPE IF EXISTS sensor_types;
DROP TYPE IF EXISTS event_type;
